@tool
extends EditorScript

func _run():
    var files = []
    var dir = DirAccess.open("res://Upgrades/Drugs")
    dir.list_dir_begin()
    var file = dir.get_next()
    while file != "":
        if not dir.current_is_dir():
            files.append("res://Upgrades/Drugs/" + file)
        file = dir.get_next()

    var f = FileAccess.open("res://Upgrades/Drugs/file_index.gd", FileAccess.WRITE)
    f.store_string("# AUTO-GENERATED by export_drugs.gd — do not edit manually\nconst FILES = " + str(files) + "\n")
