extends Node

# AUTO-GENERATED by export_drugs.gd — re-run that script when adding new drugs
const FileIndex = preload("res://Upgrades/Drugs/file_index.gd")

var drugs: Array[DrugData] = []

func _ready() -> void:
	for file in FileIndex.FILES:
		var drug = load(file) as DrugData
		if drug:
			drugs.append(drug)

func get_random_drug() -> DrugData:
	if drugs.size() == 0:
		push_error("No drugs loaded")
		return null

	var index = randi() % drugs.size()
	return drugs[index]

func get_drug_by_name(drug_name: String) -> DrugData:
	for drug in drugs:
		if drug.name == drug_name:
			return drug
	return null

func get_drug_by_id(id: StringName) -> DrugData:
	for drug in drugs:
		if drug.id == id:
			return drug
	return null
