# AUTO-GENERATED by export_drugs.gd — do not edit manually
const FILES = ["res://Upgrades/Drugs/cigarette.tres", "res://Upgrades/Drugs/file_index.gd", "res://Upgrades/Drugs/file_index.gd.uid", "res://Upgrades/Drugs/lsd.tres", "res://Upgrades/Drugs/sharpie.tres", "res://Upgrades/Drugs/tequila.tres", "res://Upgrades/Drugs/tren.tres"]
